/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hirun
 */
public class SeatBooking extends javax.swing.JFrame {

    /**
     * Creates new form SeatBooking
     */
    public SeatBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new UI.Images.PanelRound();
        panelRound2 = new UI.Images.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        panelRound3 = new UI.Images.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        MainPanel = new UI.Images.PanelRound();
        searchPane = new UI.Images.PanelRound();
        depatureLocation = new javax.swing.JComboBox<>();
        arrivalLocation = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        journeyDate = new com.github.lgooddatepicker.components.DatePicker();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        choosePane = new UI.Images.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        confirmationPane = new UI.Images.PanelRound();
        cancellPane = new UI.Images.PanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 36, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("SeatBooking");
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 204, 197));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 331, -1));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));

        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound2MouseClicked(evt);
            }
        });

        jLabel7.setText("booking");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panelRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound3MouseClicked(evt);
            }
        });

        jLabel8.setText("Cancel");

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 79, -1, 590));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        searchPane.setBackground(new java.awt.Color(153, 153, 153));
        searchPane.setLayout(null);

        depatureLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAKUMBURA", "GALLE", "MATARA", "KADUWELA", "HAKMANA", "COLOMBO", "NEGOMBO", "MIDDENIYA", "EMBILIPITIYA", "AKURESSA", "WEERAKETIYA", "DEIYANDARA", "DENIYAYA", "ELPITIYA", "KATARAGAMA", "KADAWATHA", "KANDY", "PANADURA", "KAMBURUPITIYA", "UNIVERSITY OF MORATUWA" }));
        depatureLocation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        depatureLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depatureLocationActionPerformed(evt);
            }
        });
        searchPane.add(depatureLocation);
        depatureLocation.setBounds(82, 41, 174, 31);

        arrivalLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GALLE", "MAKUMBURA", "MATARA", "KADUWELA", "COLOMBO", "HAKMANA", "NEGOMBO", "MIDDENIYA", "EMBILIPITIYA", "AKURESSA", "WEERAKETIYA", "DEIYANDARA", "DENIYAYA", "ELPITIYA", "KATARAGAMA", "KADAWATHA", "KANDY", "PANADURA", "KAMBURUPITIYA", "UNIVERSITY OF MORATUWA" }));
        arrivalLocation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchPane.add(arrivalLocation);
        arrivalLocation.setBounds(80, 140, 174, 31);

        jButton1.setText("serch");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        searchPane.add(jButton1);
        jButton1.setBounds(120, 310, 72, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        searchPane.add(jScrollPane1);
        jScrollPane1.setBounds(367, 67, 452, 316);

        jLabel2.setText("From");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchPane.add(jLabel2);
        jLabel2.setBounds(10, 50, 52, 25);

        jLabel3.setText("To");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchPane.add(jLabel3);
        jLabel3.setBounds(10, 140, 37, 25);

        jLabel4.setText("Journey Date");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchPane.add(jLabel4);
        jLabel4.setBounds(6, 221, 115, 25);
        searchPane.add(journeyDate);
        journeyDate.setBounds(127, 226, 143, 21);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        searchPane.add(jTextField1);
        jTextField1.setBounds(550, 430, 122, 22);

        jButton2.setText("Select");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        searchPane.add(jButton2);
        jButton2.setBounds(720, 420, 72, 33);

        jLabel5.setText("shedule id");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchPane.add(jLabel5);
        jLabel5.setBounds(360, 430, 130, 25);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/BackWithBoarder.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        searchPane.add(jButton5);
        jButton5.setBounds(100, 520, 100, 35);

        MainPanel.add(searchPane, "card2");

        choosePane.setBackground(new java.awt.Color(153, 153, 153));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("reseve");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel6.setText("seat no");

        javax.swing.GroupLayout choosePaneLayout = new javax.swing.GroupLayout(choosePane);
        choosePane.setLayout(choosePaneLayout);
        choosePaneLayout.setHorizontalGroup(
            choosePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choosePaneLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(choosePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(choosePaneLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButton3)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        choosePaneLayout.setVerticalGroup(
            choosePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choosePaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(choosePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel6))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        MainPanel.add(choosePane, "card3");

        confirmationPane.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout confirmationPaneLayout = new javax.swing.GroupLayout(confirmationPane);
        confirmationPane.setLayout(confirmationPaneLayout);
        confirmationPaneLayout.setHorizontalGroup(
            confirmationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        confirmationPaneLayout.setVerticalGroup(
            confirmationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        MainPanel.add(confirmationPane, "card4");

        cancellPane.setBackground(new java.awt.Color(153, 153, 153));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton4.setText("cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cancellPaneLayout = new javax.swing.GroupLayout(cancellPane);
        cancellPane.setLayout(cancellPaneLayout);
        cancellPaneLayout.setHorizontalGroup(
            cancellPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancellPaneLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancellPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton4)
                .addGap(303, 303, 303))
        );
        cancellPaneLayout.setVerticalGroup(
            cancellPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancellPaneLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(cancellPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        MainPanel.add(cancellPane, "card5");

        jPanel1.add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 79, 870, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/busreservation";
            Connection con = DriverManager.getConnection(database, "root", "root123");

            LocalDate selectedDate = journeyDate.getDate();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String jdate = selectedDate.format(formatter);

            String sql = "SELECT * FROM schedule WHERE Depature=? AND Arrival=? AND schedule_date=?";
            PreparedStatement st = con.prepareStatement(sql);

            st.setString(1, depatureLocation.getSelectedItem().toString());
            st.setString(2, arrivalLocation.getSelectedItem().toString());
            st.setString(3, jdate);

            ResultSet r = st.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            NewClass.fillTheTable(model, r);
            con.close();

        } catch (Exception ex) {
            //Error Massage
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Choose the date");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            //Class.forName("com.mysql.jdbc.Driver"); 
            String database = "jdbc:mysql://localhost:3306/busreservation";
            Connection con = DriverManager.getConnection(database, "root", "root123");
            String sql = "select * FROM seat " + "where Bus_No = (select bus from schedule where scheduleId=?) ; ";
            PreparedStatement st = con.prepareStatement(sql);

            st.setInt(1, Integer.parseInt(jTextField1.getText().toString()));

            ResultSet r = st.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            NewClass.fillTheTable(model, r);

            choosePane.setVisible(true);
            searchPane.setVisible(false);
            //SId=Integer.parseInt(scheduleId.getSelectedItem().toString());
//            while(r.next()){
//                //seat.addItem(r.getString("seatNo"));
//            }
//            
            con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String scheduleId = model.getValueAt(index, 0).toString();  //email is the 1th column in the table

        int primaryKeyValue = Integer.parseInt(model.getValueAt(index, 0).toString());

        jTextField1.setText(scheduleId);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int index = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        String SeatNo = model.getValueAt(index, 1).toString();  //email is the 1th column in the table

        int primaryKeyValue = Integer.parseInt(model.getValueAt(index, 1).toString());

        jTextField2.setText(SeatNo);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String seatno = NewClass.returnColumnValue("SeatNo", jTable2);
        String Bus_no = NewClass.returnColumnValue("Bus_No", jTable2);

        int choice = JOptionPane.showConfirmDialog(null, "Is this your final decision?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {

            try {

                Class.forName("com.mysql.jdbc.Driver");
                String database = "jdbc:mysql://localhost:3306/busreservation";
                Connection con = DriverManager.getConnection(database, "root", "root123");

                String sql = "UPDATE Seat SET Status = 'booked' where seatNo='" + seatno + "' AND Bus_No='" + Bus_no + "'";

                PreparedStatement st = con.prepareStatement(sql);
                st.executeUpdate();

                String sql2 = "SELECT * FROM seat";
                PreparedStatement st2 = con.prepareStatement(sql2);

                ResultSet r2 = st2.executeQuery();

                DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
                NewClass.fillTheTable(model2, r2);
                
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();

            }

        } else {
            System.out.println("You selected No.");
            // Add your logic for the No option here

        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void panelRound2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseClicked
        MainPanel.removeAll();
        MainPanel.add(searchPane);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_panelRound2MouseClicked

    private void panelRound3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound3MouseClicked
        MainPanel.removeAll();
        MainPanel.add(cancellPane);
        MainPanel.repaint();
        MainPanel.revalidate();

        try {

            Class.forName("com.mysql.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/busreservation";
            Connection con = DriverManager.getConnection(database, "root", "root123");

            String sql = "SELECT * FROM seat where status='booked'";

            PreparedStatement st = con.prepareStatement(sql);

            ResultSet r2 = st.executeQuery();

            DefaultTableModel model2 = (DefaultTableModel) jTable3.getModel();
            NewClass.fillTheTable(model2, r2);
            
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();

        }

    }//GEN-LAST:event_panelRound3MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int index = jTable3.getSelectedRow();
        TableModel model = jTable3.getModel();
        String bookingId = model.getValueAt(index, 1).toString();  //email is the 1th column in the table

        int primaryKeyValue = Integer.parseInt(model.getValueAt(index, 1).toString());

        jTextField3.setText(bookingId);
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String seatno = NewClass.returnColumnValue("SeatNo", jTable3);
        String Bus_no = NewClass.returnColumnValue("Bus_No", jTable3);

        int choice = JOptionPane.showConfirmDialog(null, "Is this your final decision?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {

            try {

                Class.forName("com.mysql.jdbc.Driver");
                String database = "jdbc:mysql://localhost:3306/busreservation";
                Connection con = DriverManager.getConnection(database, "root", "root123");

                String sql = "UPDATE Seat SET Status = 'unbooked' where seatNo='" + seatno + "' AND Bus_No='" + Bus_no + "'";

                PreparedStatement st = con.prepareStatement(sql);
                st.executeUpdate();

                String sql2 = "SELECT * FROM seat where status='booked'";
                PreparedStatement st2 = con.prepareStatement(sql2);

                ResultSet r2 = st2.executeQuery();

                DefaultTableModel model2 = (DefaultTableModel) jTable3.getModel();
                NewClass.fillTheTable(model2, r2);
                
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();

            }

        } else {
            System.out.println("You selected No.");
            // Add your logic for the No option here

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/BackWithBoarder2.png")));
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/BackWithBoarder.png")));
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Customerdashboard cd = new Customerdashboard();
        cd.setVisible(true);
        this.dispose();
        
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void depatureLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depatureLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depatureLocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.Images.PanelRound MainPanel;
    private javax.swing.JComboBox<String> arrivalLocation;
    private UI.Images.PanelRound cancellPane;
    private UI.Images.PanelRound choosePane;
    private UI.Images.PanelRound confirmationPane;
    private javax.swing.JComboBox<String> depatureLocation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private com.github.lgooddatepicker.components.DatePicker journeyDate;
    private UI.Images.PanelRound panelRound1;
    private UI.Images.PanelRound panelRound2;
    private UI.Images.PanelRound panelRound3;
    private UI.Images.PanelRound searchPane;
    // End of variables declaration//GEN-END:variables
}
